//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.06 at 12:27:17 AM EDT 
//


package com.sample.rest.entity.binding;

import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement(name = "unExpectedError")
public class UnExpectedError extends BaseFault {

   

}
